### PR TITLE
Add page about URL encoding

### PR DESCRIPTION
**Pull request by untitaker**

### CODE REVIEW

**Comment by dmfs** [comment]
if a page is called "URL encoding", I'd expect an article about proper URL encoding (with links to the relevant specs) in the first place.
I think what we need is an article about how to do it right and a discussion about what RFC 3986 means for *DAV applications.
Also I'd like to discuss the document on the caldeveloper mailing list. There are certain things about encoding that are still not exactly clear to me.

I think one of the problems is that you might change the meaning of a URI if you encode or decode certain characters, even if these characters are allowed without encoding in a certain location.

For example, the comma character is in the sub-delims group which is allowed in paths. So the following path would be syntactically correct:

```
/tags=tag1,tag2,tag3/
```
But it might be semantically different from (even though it decodes to the same path):

```
/tags=tag1%2Ctag2,tag3/
```
While the first path could be parsed into three tags ("tag1", "tag2" and "tag3"), the second path could be parsed into two tags ("tag1,tag2" and "tag3").

As RFC 3986 mentions, this is application/implementation specific and I think *DAV protocols in general don't support or require this kind of distinction, but I'd like to hear the opinion of others in this matter. 
There might be servers that encode certain things in the URL which require a selective encoding.

There is a DEVGUIDE TC at CalConnect (http://www.calconnect.org/tc-devguide.shtml). I think this topic is well within the scope of this TC. I'll raise this question on the TC mailing list and at the next conference.

**Comment by untitaker** [comment]
>if a page is called "URL encoding", I'd expect an article about proper URL encoding (with links to the relevant specs) in the first place.

I just assumed that knowledge since I consider URL encoding not specific to DAV. However, links to the URI RFC are sensible.

>discussion about what RFC 3986 means for *DAV applications.

I don't know what you mean by that.

>I think one of the problems is that you might change the meaning of a URI if you encode or decode certain characters, even if these characters are allowed without encoding in a certain location.

If the server is even more buggy and can't handle the properly encoded variant of their own URIs, that might have consequences. Also if two item or collection names are urlencoded variants of each other, and the described URI-normalization technique makes the client query for a different item intended. All of this can be mitigated by avoiding unsafe characters when creating collections or items. I will add this.

**Comment by dmfs** [comment]
> If the server is even more buggy and can't handle the properly encoded variant of their own URIs

That's exactly the problem. How do you know what the "properly encoded variant or their own URIs" is? Only the creator of the URI can know that (which is the server in many cases). Of course that means the server should generate correct URIs (which ownCloud apparently doesn't)

As stated before, depending on the application (or implementation), some of the characters in the sub-delims group might need encoding too, because although allowed in path names, they still might be used as delimiters and need to be encoded when they are not delimiters.

I think in the case of *DAV applications, the server is the authority of its URIs. A client (or a proxy) should not modify the encoding in any way (except for normalization as described in [RFC 3986, Section 6.2.2.2](https://tools.ietf.org/html/rfc3986#section-6.2.2.2)).

The reverse applies to filenames. In that case the client is the creator and the server should not modify the encoding of filenames. IMO it would be incorrect to return the filename `abc%40xyz@123` as `abc%40xyz%40123` or as `abc@xyz@123`.

Just consider a CardDAV client that generates (for whatever reason) file names like
```
<contact-email>@<timestamp>.vcf
```
In that case the `@` is apparently a delimiter and the `@` in the email address needs to be encoded like so
```
http://example.com/carddav/addresses/user%40example.com@1234567890123.vcf
```

IMO, any attempt to encode or decode that URI would result in different semantics.

Btw. that exactly how we handle URIs in CalDAV-Sync and CardDAV-Sync. We use whatever the server returned and we don't change any encoding. Of course that also may cause problems with broken servers, but it seems to be the most sane way to implement this and I think that's exactly how URIs should be handled. See [Section 2.4](https://tools.ietf.org/html/rfc3986#section-2.4) which states:

> Once produced, a URI is always in its percent-encoded form.

See what I mean?

**Comment by dmfs** [comment]
Here is another one from [RFC 3986, Section 2.2](https://tools.ietf.org/html/rfc3986#section-2.2):

>   URIs that differ in the replacement of a reserved character with its
>   corresponding percent-encoded octet **are not equivalent**.  Percent-
>   encoding a reserved character, or decoding a percent-encoded octet
>   that corresponds to a reserved character, will change how the URI is
>   interpreted by most applications.  Thus, characters in the reserved
>   set are protected from normalization and are therefore safe to be
>   used by scheme-specific and producer-specific algorithms for
>   delimiting data subcomponents within a URI.

**Comment by untitaker** [comment]
ownCloud mangles the requested URLs in a way that makes `%40`, `%2540` and `@` indistinguishable from each other. If I disabled all normalization and sanity checks and trusted the server to do the right thing, I might accidentally ignore items during synchronization.

Despite your example of `%40` and `@` having different semantics, this is in the RFC:

>The percent-encoding mechanism (Section 2.1) is a frequent source of variance among otherwise identical URIs.  In addition to the case normalization issue noted above, some URI producers percent-encode octets that do not require percent-encoding, resulting in URIs that are equivalent to their non-encoded counterparts.  These URIs should be normalized by decoding any percent-encoded octet that corresponds to an unreserved character, as described in Section 2.3.

It is also very close to what my document recommends (although much less aggressive).

**Comment by untitaker** [comment]
Really the only difference is whether to treat `@` as reserved character or not. The problem here is that `@` has no special meaning in paths and is unnecessarily encoded. I also apply the whole normalization thing only to the path segment -- another detail that is worth mentioning.

**Comment by untitaker** [comment]
Also FWIW also nginx already mangles `%40` and `@` (but not `%2540`).

**Comment by dmfs** [comment]
> ownCloud mangles the requested URLs in a way that makes %40, %2540 and @ indistinguishable from each other.

Yes, that's clearly a bug.

> some URI producers percent-encode octets that do not require percent-encoding, resulting in URIs that are equivalent to their non-encoded counterparts

That clearly refers to unreserved characters. Otherwise these URI wouldn't be equivalent as per section 2.2. So if you normalize such a URI, you should only look for characters in the unreserved range.

>  Really the only difference is whether to treat @ as reserved character or not. 

It is, [Section 2.2](https://tools.ietf.org/html/rfc3986#section-2.2) leaves no doubt about that:  

```
      reserved    = gen-delims / sub-delims

      gen-delims  = ":" / "/" / "?" / "#" / "[" / "]" / "@"

      sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"
                  / "*" / "+" / "," / ";" / "="
```

Even though [Section 3.3](https://tools.ietf.org/html/rfc3986#section-3.3) explicitly allows `@` in paths, it's still a reserved character (just like '0' is still a digit ;-) )

> The problem here is that @ has no special meaning in paths and is unnecessarily encoded. 

It has no special meaning to your application nor to ownCloud, but it might have one for other clients.

Actually I think that's not 100% true. From what I've seen you're using it as a delimiter (you're not using %40 as the delimiter, right?), so it has kind of a special meaning in your application.

> Also FWIW also nginx already mangles %40 and @ (but not %2540).

I'd call that a bug in nginx. The RFC clearly says that this is not valid, because the URI is not equivalent afterwards.

**Comment by untitaker** [comment]
>It is, Section 2.2 leaves no doubt about that

My phrasing was ambiguous, I meant: Whether to treat it as equivalent to `%40` when occuring inside the path segment, since it has no meaning (for the URI parser). I'd argue that any application whose behavior changes depending whether `@` is encoded or not is already broken in real-life usage.

Not normalizing an URL to some extent is not an option for me. When given a multistatus response, I need to match all returned hrefs with the hrefs I sent. This is impossible if ownCloud changes `@` to `%40` or even `%2540`.

>I'd call that a bug in nginx. The RFC clearly says that this is not valid, because the URI is not equivalent afterwards.

I rather suppose that's an intentional workaround.

**Comment by mitsuhiko** [comment]
To give my feedback on this: you cannot assign different behavior to `@` and `%40` or `/` and `%2f` even if an RFC at one point might have said to do so.  The reason for that is that all software out there that processes URLs needs to do this in unquoted form and by doing that you lose the information what was quoted originally or not.

So it does not matter what the RFC says, it cannot be done in the real world.  No proxy or application server is going to support this.  You can only do that at the very end maybe (your own application) but anything that is there in the front will break it.

**Comment by dmfs** [comment]
You both may be right about real life applications, but we're discussing a wiki page about URI encoding. I think such a page should show how to do it correctly and back up any claims with quotes from the specs in the first place.

A separate section could give guidance on how to avoid problems with improper encodings, i.e. avoid using `@` in URLs in own applications. The wiki should not encourage developers to apply techniques that might make it worse. Decoding a URI is not a good idea (unless you know about any special semantics, because you're the authority of that URI or you know about it) and should not be encouraged. Apart from the obvious decoding issue that you may loose special semantics, there are other issues like character encoding (i.e. when you come across `%C3%A4` how can you know if that's an encoded UTF-8 `ä` or if it's a character sequence from any other charset?).
If anything, every developer should decide carefully whether decoding is really required and maybe only decode selectively any sequences that are known to be broken.

In the end the goal should be that everyone handles encoding correctly rather than everyone has a workaround for encoding issues. If a popular product like ownCloud is broken even though the issue is known for a long time, we should bring that to people's attention.

Also, I'm pretty sure that every major web server and proxy server has an option to pass encoded characters though without modification. I think for nginx that's the proxy_pass directive. So it's not an issue per se, but more like a workaround that has become the default, unfortunately.

(btw. does ownCloud double encode other special characters too or only `@`?)

**Comment by untitaker** [comment]
>You both may be right about real life applications, but we're discussing a wiki page about URI encoding. I think such a page should show how to do it correctly and back up any claims with quotes from the specs in the first place.

I see, when I opened #3 I rather meant to write documentation about real-world problems, as I believe everybody is already able to read the spec themselves. But since spec-compliant behavior means *doing absolutely nothing*, what else should I add to this page?

>(i.e. when you come across %C3%A4 how can you know if that's an encoded UTF-8 ä or if it's a character sequence from any other charset?).

I couldn't find anything in the RFC, but *in practice* (:P) every piece of Python software I've come across seems to assume UTF-8.

>(btw. does ownCloud double encode other special characters too or only @?)

I haven't tested, but I believe it's everything. The bugfix was to remove an `urlencode` call, which I hope is deployed soon.

**Comment by untitaker** [comment]
I've now added a small "Theory" section to the RFC.

**Comment by dmfs** [comment]
Thanks. I'll probably add some more text about URL encoding.

Also, I think it makes sense to move the topic to a page called `RFC 3986`, since that's what this page is all about. What do you think?

**Comment by untitaker** [comment]
I can do those additions, but I'm not sure what to write.

On 24 August 2015 08:00:36 CEST, Marten Gajda <notifications@github.com> wrote:
>Thanks. I'll probably add some more text about URL encoding.
>
>Also, I think it makes sense to move the topic to a page called `RFC
>3986`, since that's what this page is all about. What do you think?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/dmfs/davwiki/pull/4#issuecomment-134049969

-- 
Sent from my phone. Please excuse my brevity.

**Comment by untitaker** [comment]
Also i'd like the page titles to be "human readable", although I do see the point of associating each page with an RFC.

On 24 August 2015 08:00:36 CEST, Marten Gajda <notifications@github.com> wrote:
>Thanks. I'll probably add some more text about URL encoding.
>
>Also, I think it makes sense to move the topic to a page called `RFC
>3986`, since that's what this page is all about. What do you think?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/dmfs/davwiki/pull/4#issuecomment-134049969

-- 
Sent from my phone. Please excuse my brevity.

**Comment by dmfs** [comment]
I still think we should have a page about RFC 3986 though. It could link to the encoding page or the encoding page could be renamed. Not sure what's better yet.

**Pull request merged**
